### PR TITLE
Disney Plus and YouTube Links

### PR DESCRIPTION
**Pull request by MrRubberDucky99**
I have created code that adds buttons below the name of each movie with links to watch it on YouTube or Disney Plus (If one isn't available it will not show up). I have used similar code for adding both the Disney and YouTube links and so more services can be added by copying and editing the code.

Links do not show for TV shows though they are in `data.json`, however, this could probably be fixed with some time put into it.

I have also updated all packages via `npm audit fix --force`

The links are currently just images of the services used (Amazon prime is in there from testing), you may wish to change these to buttons

### CODE REVIEW

**Review by dispossible — COMMENTED** [review]
Hi Ducky,

As I outlined in my response on your question about hosting, there are some hurdles to overcome before I will accept adding links to the timeline.

> 1. I have been concerned that it could prove very hard to find a link for every show and having only some of them linked up could be annoying. I don't like the inconsistency.
> 2. There may be a whole bunch of shows with regional variations in where they are streamable from. I know for instance the Spiderman films are a pain to get a hold of in the UK (where I am) and are on different services in the US. To name just 2 regions.
> 3. It adds an extra maintenance burden if any of the links get broken over time, which isn't easy to test for if they are only broken in other regions.

I don't believe you have addressed these points.

On point 1, large amounts of the shows are lacking links, where I would prefer the consistency of having, if not all, but the majority of the cards linked. Most of the Netflix series can potentially be linked up and that could break the back of getting most of the cards linked.

Point 2, I tested the YouTube links from Germany (via VPN) and all the ones I checked ended up on "video not available" pages. They do exist but you need to link to the German language version. Dealing with this regional variation is a massive headache. For the Disney links they appear to provide redirects internally when attempting to arrive at the incorrect regional URL, however I was unable to verify this fully as they appear to be employing countermeasures against my VPN.

Point 3 ties in with point 2, and it causes additional ongoing maintenance of the links on top of the other data. I maintain this in my spare time, so adding more data to keep in check takes more of my time. I realise you can't do much to address this, but it does contribute to my reluctance to accept the feature.

I do also have a few critiques on your code that I would want tidied up before accepting, to maintain the naming conventions and consistency of the codebase, but unless you want that as feedback I'm going to close this request for the points outlined above.

Thank you for the interest in my project, and I really don't want to discourage you from contributing. Is this a feature you are particularly keen to see in my site, or were you just looking to contribute? There are features I have had in mind for the site, which if you are looking to contribute we could discuss.

Thanks,
Timothy

**Comment by MrRubberDucky99** [comment]
Are there any feature I can work on for you?

**Comment by dispossible** [comment]
Hey Ducky,

Sorry for the slow reply, had a bit of a busy week.

So a feature that I have been meaning to put some time into is the filtering system. I haven't really changed it since about when Phase 2 was coming out. The landscape of the shows has changed a bit since then.

So if you are up for it, it would be really helpful to expand on the data to add in a property for which 'Phase' each show is in as well as updating the 'type's. I was thinking the new set of types would look something like:

- 'Film'
- 'MCU TV' (Disney+ & AoS)
- 'Netflix TV' (Better name? 'Defenders TV')
- 'Other TV'
- 'Web Series'
- 'Shorts'

**Comment by MrRubberDucky99** [comment]
What do you think of sorting by timeline as well as type, eg the 2012 Loki series is a different timeline or AoS Season 6+ is a different timeline, maybe using colour coding to show different timelines and where they diverge?

**Comment by dispossible** [comment]
That's an interesting idea. AoS is something of an outlier anyway on it's plot points and Loki isn't released yet, so I don't know how needed it is to differentiate between the timelines just yet. So right now I'd hold fire on doing that, but given the upcoming Phase 4 is reportedly focusing on the multiverse it may be something to revisit after a few more Phase 4 shows are out.

**Pull request closed without merging**
